name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Checkout repository
    - name: Checkout Code
      uses: actions/checkout@v3

    # Setup Node.js environment
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Install dependencies
    - name: Install Dependencies
      run: npm install

    # Run Linter
    - name: Run Linter
      run: npm run lint

    # Run Tests
    - name: Run Tests
      run: npm test

    # Generate Test Coverage Report (optional)
    - name: Generate Coverage Report
      run: npm run coverage
